package com.sri.gradle.daikon.tasks;

import com.sri.gradle.daikon.Constants;
import com.sri.gradle.daikon.utils.JavaProjectHelper;
import java.io.File;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.gradle.api.Project;
import org.gradle.api.file.Directory;
import org.gradle.api.file.FileCollection;
import org.gradle.api.file.SourceDirectorySet;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.compile.JavaCompile;

@SuppressWarnings("UnstableApiUsage")
public class CompileTestJavaTaskMutator {

  private final FileCollection compileJavaClasspath;
  private final JavaProjectHelper projectHelper;

  public CompileTestJavaTaskMutator(Project project, FileCollection compileJavaClasspath) {
    this.compileJavaClasspath = compileJavaClasspath;
    this.projectHelper = new JavaProjectHelper(project);
  }

  public void mutateJavaCompileTask(JavaCompile javaCompile) {
    configureCompilerArgs(javaCompile);
    configureClasspath(javaCompile);
    configureSourcesAndDestinations(javaCompile);
  }

  private void configureCompilerArgs(JavaCompile javaCompile) {
    List<String> compilerArgs = buildCompilerArgs(javaCompile);
    javaCompile.getOptions().setCompilerArgs(compilerArgs);
  }

  private void configureClasspath(JavaCompile javaCompile) {
    Set<File> runtimeClasspath = getProjectHelper().getRuntimeClasspath();
    javaCompile.setClasspath(getProjectHelper().getProject().files(this.compileJavaClasspath, runtimeClasspath));
  }

  // Setting the sourcepath and source set is necessary when using forked compilation for
  // AutoGeneratedTestDriver.java
  private void configureSourcesAndDestinations(JavaCompile javaCompile) {
    final Directory testClassesDir = getProjectHelper().getBuildTestDir();
    javaCompile.setDestinationDir(testClassesDir.getAsFile());

    SourceDirectorySet sds =
        javaCompile
            .getProject()
            .getObjects()
            .sourceDirectorySet("driver", "driver")
            .srcDir(getProjectHelper().getDriverDir());

    final SourceSet sourceSet = getProjectHelper().getTestSourceSet();
    final Set<File> newSourceSet = new HashSet<>(sourceSet.getJava().getSrcDirs());
    newSourceSet.add(getProjectHelper().getDriverDir());
    newSourceSet
        .stream()
        .map(srcDir -> srcDir.toPath().resolve(Constants.TEST_DRIVER_CLASSNAME + ".java"))
        .filter(Files::exists)
        .findFirst()
        .ifPresent(
            path -> {
              javaCompile.setSource(sds);
              javaCompile.getOptions().setSourcepath(javaCompile.getProject().files(path.getParent()));
            });
  }

  private static List<String> buildCompilerArgs(JavaCompile javaCompile) {
    return new ArrayList<>(javaCompile.getOptions().getCompilerArgs());
  }

  JavaProjectHelper getProjectHelper(){
    return projectHelper;
  }
}
