package com.sri.gradle.tasks;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.Formatter;
import java.util.List;

/**
 * Wraps DyComp, Chicory, and Daikon into a single work:
 *
 * generateLikelyInvariants(path/to/test/classes)
 *  .givenSysClasspath(file1, file2, ...)
 *  .intoDir(..)
 */
public interface WorkExecutor {
  /**
   * Caches an error.
   * @param cause thrown exception.
   */
  void addError(Throwable cause);

  /**
   * Installs a new Task configuration
   *
   * @param configuration install configuration into task executor.
   */
  default void install(WorkConfiguration configuration){
    configuration.configure(this);
  }

  /**
   * Likely-Invariants extraction is applied to project's test classes. These test
   * classes were automatically generated by Randoop and their .class files should
   * be already available.
   *
   * @param testClassesDir where to look for .class files.
   * @return a new WorkBuilder object.
   */
  WorkBuilder generateLikelyInvariants(File testClassesDir);

  /**
   * Executes installed configuration
   */
  void execute() throws ConfigurationError;

  class ConfigurationError extends RuntimeException {
    ConfigurationError(Collection<Throwable> throwables){
      super(createErrorMessage(throwables));
    }

    private static String createErrorMessage(Collection<Throwable> errorMessages) {
      final List<Throwable> encounteredErrors = new ArrayList<>(errorMessages);
      if(!encounteredErrors.isEmpty()){
        encounteredErrors.sort(new ThrowableComparator());
      }

      final Formatter messageFormatter = new Formatter();
      messageFormatter.format("Work Opening configuration errors:%n%n");
      int index = 1;

      for (Throwable errorMessage : encounteredErrors) {
        final String    message = errorMessage.getLocalizedMessage();
        final String    line    = "line " + message.charAt(message.lastIndexOf("line") + 5);
        messageFormatter.format("%s) Error at %s:%n", index++, line).format(" %s%n%n", message);
      }

      return messageFormatter.format("%s error[s]", encounteredErrors.size()).toString();
    }
  }


  class ThrowableComparator implements Comparator<Throwable> {
    @Override public int compare(Throwable a, Throwable b) {
      return a.getMessage().compareTo(b.getMessage());
    }
  }
}
